# Runs Bazel tests for DeepMind Lab

language: c++

dist: bionic

jdk:
  - oraclejdk8

jobs:
  include:
    - compiler: clang
      env: BAZELFLAGS="--copt=-Wno-uninitialized --copt=-Wno-sign-compare"
    - compiler: gcc
      env: BAZELFLAGS="--copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare"

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
      - libffi-dev
      - gettext
      - freeglut3-dev
      - libsdl2-dev
      - libosmesa6-dev
      - python-dev
      - python-numpy
      - python-pil
      - python3-dev
      - python3-numpy
      - python3-pil

script:
  - bazel --bazelrc=.travis.bazelrc build ${BAZELFLAGS} //... ;
  - bazel --bazelrc=.travis.bazelrc test  ${BAZELFLAGS} //... ;
  - bazel --bazelrc=.travis.bazelrc run   ${BAZELFLAGS} --define headless=osmesa //:python_random_agent ;
